export const state = {
  rows: [],
  filteredRows: [],
  speakerLeft: "사용자1",
  speakerRight: "사용자2",
  groupDays: 15,
  view: "thread",
  query: "",
  field: "all",
  sort: "date_desc",
  quickFilter: "all",
  tokenCount: 0,
  searchMs: 0,
  sourceName: "",
}
